# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20180723_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyofficer',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'teacher'), ('HEADTEACHER', 'headteacher'), ('COUNTYOFFICER', 'countyofficer')], max_length=60),
        ),
        migrations.AlterField(
            model_name='headteacher',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'teacher'), ('HEADTEACHER', 'headteacher'), ('COUNTYOFFICER', 'countyofficer')], max_length=60),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'teacher'), ('HEADTEACHER', 'headteacher'), ('COUNTYOFFICER', 'countyofficer')], max_length=60),
        ),
    ]
